# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a:\开发\Student-Recognition-System\login_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(379, 411)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);")
        self.lab_error_hint_2 = QtWidgets.QLabel(Dialog)
        self.lab_error_hint_2.setGeometry(QtCore.QRect(40, 300, 325, 16))
        self.lab_error_hint_2.setText("")
        self.lab_error_hint_2.setObjectName("lab_error_hint_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 60, 164, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.lab_error_hint_1 = QtWidgets.QLabel(Dialog)
        self.lab_error_hint_1.setGeometry(QtCore.QRect(40, 220, 325, 16))
        self.lab_error_hint_1.setText("")
        self.lab_error_hint_1.setObjectName("lab_error_hint_1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 180, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.led_userName = QtWidgets.QLineEdit(Dialog)
        self.led_userName.setGeometry(QtCore.QRect(100, 180, 250, 30))
        self.led_userName.setStyleSheet("border-radius: 10px; \n"
"border: 2px groove gray;\n"
"border-style: outset;")
        self.led_userName.setText("")
        self.led_userName.setObjectName("led_userName")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 250, 34, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.led_passwd = QtWidgets.QLineEdit(Dialog)
        self.led_passwd.setGeometry(QtCore.QRect(100, 248, 250, 30))
        self.led_passwd.setStyleSheet("border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;")
        self.led_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.led_passwd.setObjectName("led_passwd")
        self.btn_login = QtWidgets.QPushButton(Dialog)
        self.btn_login.setGeometry(QtCore.QRect(120, 350, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("border-radius: 10px;  \n"
"border: 2px groove gray;\n"
"border-style: outset;")
        self.btn_login.setObjectName("btn_login")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 250, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.bnt_minimize = QtWidgets.QPushButton(Dialog)
        self.bnt_minimize.setGeometry(QtCore.QRect(320, 0, 30, 30))
        self.bnt_minimize.setMinimumSize(QtCore.QSize(30, 30))
        self.bnt_minimize.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.bnt_minimize.setFont(font)
        self.bnt_minimize.setStyleSheet("background-color: rgb(46, 47, 48);\n"
"color: rgb(255, 255, 255);")
        self.bnt_minimize.setObjectName("bnt_minimize")
        self.bnt_close = QtWidgets.QPushButton(Dialog)
        self.bnt_close.setGeometry(QtCore.QRect(350, 0, 30, 30))
        self.bnt_close.setMinimumSize(QtCore.QSize(30, 30))
        self.bnt_close.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.bnt_close.setFont(font)
        self.bnt_close.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(217, 0, 0);")
        self.bnt_close.setObjectName("bnt_close")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "登录账号"))
        self.label.setText(_translate("Dialog", "用户名"))
        self.label_2.setText(_translate("Dialog", "密码"))
        self.btn_login.setText(_translate("Dialog", "登录"))
        self.label_4.setText(_translate("Dialog", "学生辨识系统-登录你的账号"))
        self.bnt_minimize.setText(_translate("Dialog", "-"))
        self.bnt_close.setText(_translate("Dialog", "×"))
